# Generated by Django 5.0.6 on 2024-05-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_carmodels_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodels',
            name='description',
            field=models.TextField(),
        ),
    ]
