# Generated by Django 5.0.6 on 2024-05-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_carmodels_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='logo',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
